import type { ReactElement } from 'react';
import type { MapLocation } from '@/ui/components/map/types';
import type { SaveData } from '@/parser/types';

export const Journal: {
  name: string;
  desc: string;
  gameId: string;
  img: () => ReactElement;
  markers: MapLocation[];
  isCounted: boolean | 'steel';
  missable?: (saveData: SaveData) => boolean;
  required: number;
  act: 1 | 2 | 3;
}[] = [
  {
    name: 'Mossgrub',
    desc: 'TODO',
    gameId: 'MossBone Crawler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Massive Mossgrub',
    desc: 'TODO',
    gameId: 'MossBone Crawler Fat',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 2,
  },
  {
    name: 'Mossmir',
    desc: 'TODO',
    gameId: 'MossBone Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Moss Mother',
    desc: 'TODO',
    gameId: 'Mossbone Mother',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 1,
  },
  {
    name: 'Aknid',
    desc: 'TODO',
    gameId: 'Aspid Collector',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Skull Scuttler',
    desc: 'TODO',
    gameId: 'Bone Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 35,
    act: 1,
  },
  {
    name: 'Skullwing',
    desc: 'TODO',
    gameId: 'Bone Goomba Bounce Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Skull Brute',
    desc: 'TODO',
    gameId: 'Bone Goomba Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Skull Tyrant',
    desc: 'TODO',
    gameId: 'Skull King',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Kilik',
    desc: 'TODO',
    gameId: 'Bone Crawler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Beastfly',
    desc: 'TODO',
    gameId: 'Bone Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 1,
  },
  {
    name: 'Savage Beastfly',
    desc: 'TODO',
    gameId: 'Bone Flyer Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 1,
  },
  {
    name: 'Caranid',
    desc: 'TODO',
    gameId: 'Bone Circler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Vicious Caranid',
    desc: 'TODO',
    gameId: 'Bone Circler Vicious',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Hardbone Hopper',
    desc: 'TODO',
    gameId: 'Bone Hopper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Hardbone Elder',
    desc: 'TODO',
    gameId: 'Bone Hopper Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Tarmite',
    desc: 'TODO',
    gameId: 'Bone Spitter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Mawling',
    desc: 'TODO',
    gameId: 'Bone Roller',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 1,
  },
  {
    name: 'Marrowmaw',
    desc: 'TODO',
    gameId: 'Bone Thumper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 1,
  },
  {
    name: 'Hoker',
    desc: 'TODO',
    gameId: 'Spine Floater',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Flintbeetle',
    desc: 'TODO',
    gameId: 'Rock Roller',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 1,
  },
  {
    name: 'Rhinogrund',
    desc: 'TODO',
    gameId: 'Rhino',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 2,
  },
  {
    name: 'Gromling',
    desc: 'TODO',
    gameId: 'Crypt Worm',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Grom',
    desc: 'TODO',
    gameId: 'Bone Worm',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Bell Beast',
    desc: 'TODO',
    gameId: 'Bone Beast',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Pilgrim Groveller',
    desc: 'TODO',
    gameId: 'Pilgrim 13',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 35,
    act: 1,
  },
  {
    name: 'Pilgrim Pouncer',
    desc: 'TODO',
    gameId: 'Pilgrim 11',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 35,
    act: 1,
  },
  {
    name: 'Pilgrim Hornfly',
    desc: 'TODO',
    gameId: 'Pilgrim 14',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Pilgrim Hulk',
    desc: 'TODO',
    gameId: 'Pilgrim 12',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Pilgrim Bellbearer',
    desc: 'TODO',
    gameId: 'Pilgrim Bell Thrower',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Winged Pilgrim',
    desc: 'TODO',
    gameId: 'Pilgrim Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Elder Pilgrim',
    desc: 'TODO',
    gameId: 'Pilgrim 15',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 5,
    act: 1,
  },
  {
    name: 'Winged Pilgrim Bellbearer',
    desc: 'TODO',
    gameId: 'Pilgrim Bellthrower Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Pilgrim Hiker',
    desc: 'TODO',
    gameId: 'Pilgrim Hiker',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Pilgrim Guide',
    desc: 'TODO',
    gameId: 'Pilgrim StaffWielder',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Overgrown Pilgrim',
    desc: 'TODO',
    gameId: 'Pilgrim Moss Spitter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Covetous Pilgrim',
    desc: 'TODO',
    gameId: 'Rosary Pilgrim',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 1,
  },
  {
    name: 'Snitchfly',
    desc: 'TODO',
    gameId: 'Rosary Thief',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 1,
  },
  {
    name: 'Lavalug',
    desc: 'TODO',
    gameId: 'Tar Slug',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 1,
  },
  {
    name: 'Lavalarga',
    desc: 'TODO',
    gameId: 'Tar Slug Huge',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Smelt Shoveller',
    desc: 'TODO',
    gameId: 'Dock Worker',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Flintstone Flyer',
    desc: 'TODO',
    gameId: 'Dock Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Flintflame Flyer',
    desc: 'TODO',
    gameId: 'Dock Bomber',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Smokerock Sifter',
    desc: 'TODO',
    gameId: 'Shield Dock Worker',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Deep Diver',
    desc: 'TODO',
    gameId: 'Dock Charger',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 5,
    act: 1,
  },
  {
    name: 'Forebrothers Signis & Gron',
    desc: 'TODO',
    gameId: 'Dock Guard Thrower',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Cragglite',
    desc: 'TODO',
    gameId: 'Small Crab',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 1,
  },
  {
    name: 'Craggler',
    desc: 'TODO',
    gameId: 'Roof Crab',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Brushflit',
    desc: 'TODO',
    gameId: 'Fields Flock Flyers',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Fertid',
    desc: 'TODO',
    gameId: 'Fields Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Flapping Fertid',
    desc: 'TODO',
    gameId: 'Fields Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Fourth Chorus',
    desc: 'TODO',
    gameId: 'Song Golem',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Skarrlid',
    desc: 'TODO',
    gameId: 'Bone Hunter Tiny',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Skarrwing',
    desc: 'TODO',
    gameId: 'Bone Hunter Buzzer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 1,
  },
  {
    name: 'Skarr Scout',
    desc: 'TODO',
    gameId: 'Bone Hunter Child',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Skarr Stalker',
    desc: 'TODO',
    gameId: 'Bone Hunter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Spear Skarr',
    desc: 'TODO',
    gameId: 'Bone Hunter Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Skarrgard',
    desc: 'TODO',
    gameId: 'Bone Hunter Throw',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 1,
  },
  {
    name: 'Gurr the Outcast',
    desc: 'TODO',
    gameId: 'Bone Hunter Trapper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Last Claw',
    desc: 'TODO',
    gameId: 'Bone Hunter Chief',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Skarrsinger Karmelita',
    desc: 'TODO',
    gameId: 'Hunter Queen',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Mite',
    desc: 'TODO',
    gameId: 'Mite',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 1,
  },
  {
    name: 'Fluttermite',
    desc: 'TODO',
    gameId: 'Mitefly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Mitemother',
    desc: 'TODO',
    gameId: 'Gnat Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Dreg Catcher',
    desc: 'TODO',
    gameId: 'Farmer Catcher',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Silk Snipper',
    desc: 'TODO',
    gameId: 'Farmer Scissors',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Thread Raker',
    desc: 'TODO',
    gameId: 'Farmer Centipede',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Moorwing',
    desc: 'TODO',
    gameId: 'Vampire Gnat',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Wisp',
    desc: 'TODO',
    gameId: 'Wisp',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Burning Bug',
    desc: 'TODO',
    gameId: 'Farmer Wisp',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Father of the Flame',
    desc: 'TODO',
    gameId: 'Wisp Pyre Effigy',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Craw',
    desc: 'TODO',
    gameId: 'Crow',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Tallcraw',
    desc: 'TODO',
    gameId: 'Crowman',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Squatcraw',
    desc: 'TODO',
    gameId: 'Crowman Dagger',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Craw Juror',
    desc: 'TODO',
    gameId: 'Crowman Juror Tiny',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 3,
  },
  {
    name: 'Tallcraw Juror',
    desc: 'TODO',
    gameId: 'Crowman Juror',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Squatcraw Juror',
    desc: 'TODO',
    gameId: 'Crowman Dagger Juror',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 3,
  },
  {
    name: 'Crawfather',
    desc: 'TODO',
    gameId: 'Crawfather',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Muckmaggot',
    desc: 'TODO',
    gameId: 'Maggots',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 81,
    act: 1,
  },
  {
    name: 'Slubberlug',
    desc: 'TODO',
    gameId: 'Dustroach Pollywog',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Muckroach',
    desc: 'TODO',
    gameId: 'Dustroach',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Bloatroach',
    desc: 'TODO',
    gameId: 'Bloat Roach',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Roachcatcher',
    desc: 'TODO',
    gameId: 'Roachfeeder Short',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Roachfeeder',
    desc: 'TODO',
    gameId: 'Roachfeeder Tall',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Roachkeeper',
    desc: 'TODO',
    gameId: 'Roachkeeper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Roachserver',
    desc: 'TODO',
    gameId: 'Roachkeeper Chef Tiny',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Disgraced Chef Lugoli',
    desc: 'TODO',
    gameId: 'Roachkeeper Chef',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Wraith',
    desc: 'TODO',
    gameId: 'Wraith',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Mothleaf Lagnia',
    desc: 'TODO',
    gameId: 'Swamp Drifter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Miremite',
    desc: 'TODO',
    gameId: 'Swamp Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Swamp Squit',
    desc: 'TODO',
    gameId: 'Swamp Mosquito',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 1,
  },
  {
    name: 'Spit Squit',
    desc: 'TODO',
    gameId: 'Swamp Mosquito Skinny',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Stilkin',
    desc: 'TODO',
    gameId: 'Swamp Muckman',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Stilkin Trapper',
    desc: 'TODO',
    gameId: 'Swamp Muckman Tall',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Groal the Great',
    desc: 'TODO',
    gameId: 'Swamp Shaman',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Barnak',
    desc: 'TODO',
    gameId: 'Swamp Barnacle',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Ductsucker',
    desc: 'TODO',
    gameId: 'Swamp Ductsucker',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 2,
  },
  {
    name: 'Pond Skipper',
    desc: 'TODO',
    gameId: 'Pond Skater',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Pondcatcher',
    desc: 'TODO',
    gameId: 'Pilgrim Fisher',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Shellwood Gnat',
    desc: 'TODO',
    gameId: 'Shellwood Gnat',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Wood Wasp',
    desc: 'TODO',
    gameId: 'Shellwood Wasp',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 1,
  },
  {
    name: 'Splinter',
    desc: 'TODO',
    gameId: 'Stick Insect',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 1,
  },
  {
    name: 'Splinterhorn',
    desc: 'TODO',
    gameId: 'Stick Insect Charger',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Splinterbark',
    desc: 'TODO',
    gameId: 'Stick Insect Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Sister Splinter',
    desc: 'TODO',
    gameId: 'Splinter Queen',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Phacia',
    desc: 'TODO',
    gameId: 'Flower Drifter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Pollenica',
    desc: 'TODO',
    gameId: 'Bloom Shooter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Gahlia',
    desc: 'TODO',
    gameId: 'Bloom Puncher',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Shrine Guardian Seth',
    desc: 'TODO',
    gameId: 'Seth',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Nyleth',
    desc: 'TODO',
    gameId: 'Flower Queen',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Furm',
    desc: 'TODO',
    gameId: 'Bell Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Winged Furm',
    desc: 'TODO',
    gameId: 'Bell Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 1,
  },
  {
    name: 'Pharlid',
    desc: 'TODO',
    gameId: 'Blade Spider',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 1,
  },
  {
    name: 'Pharlid Diver',
    desc: 'TODO',
    gameId: 'Blade Spider Hang',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Shardillard',
    desc: 'TODO',
    gameId: 'Shell Fossil Mimic',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 1,
  },
  {
    name: 'Sandcarver',
    desc: 'TODO',
    gameId: 'Sand Centipede',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 41,
    act: 1,
  },
  {
    name: 'Squirrm',
    desc: 'TODO',
    gameId: 'Coral Judge Child',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 1,
  },
  {
    name: 'Judge',
    desc: 'TODO',
    gameId: 'Coral Judge',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Last Judge',
    desc: 'TODO',
    gameId: 'Last Judge',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Coral Furm',
    desc: 'TODO',
    gameId: 'Coral Spike Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Driznit',
    desc: 'TODO',
    gameId: 'Coral Conch Shooter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 1,
  },
  {
    name: 'Driznarga',
    desc: 'TODO',
    gameId: 'Coral Conch Shooter Heavy',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 14,
    act: 2,
  },
  {
    name: 'Pokenabbin',
    desc: 'TODO',
    gameId: 'Coral Conch Stabber',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 16,
    act: 2,
  },
  {
    name: 'Conchfly',
    desc: 'TODO',
    gameId: 'Coral Conch Driller',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Great Conchfly',
    desc: 'TODO',
    gameId: 'Coral Conch Driller Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 2,
  },
  {
    name: 'Crustcrawler',
    desc: 'TODO',
    gameId: 'Coral Goombas',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Crustcrag',
    desc: 'TODO',
    gameId: 'Coral Goomba Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 2,
  },
  {
    name: 'Kai',
    desc: 'TODO',
    gameId: 'Coral Swimmer Fat',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Spinebeak Kai',
    desc: 'TODO',
    gameId: 'Poke Swimmer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Steelspine Kai',
    desc: 'TODO',
    gameId: 'Spike Swimmer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 3,
  },
  {
    name: 'Yuma',
    desc: 'TODO',
    gameId: 'Coral Swimmer Small',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 16,
    act: 3,
  },
  {
    name: 'Yumama',
    desc: 'TODO',
    gameId: 'Coral Big Jellyfish',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 3,
  },
  {
    name: 'Karaka',
    desc: 'TODO',
    gameId: 'Coral Warrior',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Kakri',
    desc: 'TODO',
    gameId: 'Coral Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Yago',
    desc: 'TODO',
    gameId: 'Coral Flyer Throw',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 3,
  },
  {
    name: 'Karak Gor',
    desc: 'TODO',
    gameId: 'Coral Brawler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 3,
  },
  {
    name: 'Alita',
    desc: 'TODO',
    gameId: 'Coral Hunter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Corrcrust Karaka',
    desc: 'TODO',
    gameId: 'Coral Bubble Brute',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Crust King Khann',
    desc: 'TODO',
    gameId: 'Coral King',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Watcher at the Edge',
    desc: 'TODO',
    gameId: 'Coral Warrior Grey',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Voltvyrm',
    desc: 'TODO',
    gameId: 'Zap Core Enemy',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Drapefly',
    desc: 'TODO',
    gameId: 'Citadel Bat',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 2,
  },
  {
    name: 'Drapelord',
    desc: 'TODO',
    gameId: 'Citadel Bat Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 2,
  },
  {
    name: 'Drapemite',
    desc: 'TODO',
    gameId: 'Mite Heavy',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Giant Drapemite',
    desc: 'TODO',
    gameId: 'Understore Mite Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 2,
  },
  {
    name: 'Underworker',
    desc: 'TODO',
    gameId: 'Understore Small',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Underscrub',
    desc: 'TODO',
    gameId: 'Pilgrim 13 Understore',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Undersweep',
    desc: 'TODO',
    gameId: 'Pilgrim Staff Understore',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Underpoke',
    desc: 'TODO',
    gameId: 'Understore Poker',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Underloft',
    desc: 'TODO',
    gameId: 'Understore Thrower',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Undercrank',
    desc: 'TODO',
    gameId: 'Understore Heavy',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 2,
  },
  {
    name: 'Envoy',
    desc: 'TODO',
    gameId: 'Song Pilgrim 01',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Choir Pouncer',
    desc: 'TODO',
    gameId: 'Pilgrim 11 Song',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 2,
  },
  {
    name: 'Choir Hornhead',
    desc: 'TODO',
    gameId: 'Pilgrim 12 Song',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Choir Bellbearer',
    desc: 'TODO',
    gameId: 'Pilgrim 13 Song',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Choir Flyer',
    desc: 'TODO',
    gameId: 'Pilgrim 14 Song',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Choir Elder',
    desc: 'TODO',
    gameId: 'Pilgrim Stomper Song',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 2,
  },
  {
    name: 'Choristor',
    desc: 'TODO',
    gameId: 'Song Pilgrim 03',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Reed',
    desc: 'TODO',
    gameId: 'Song Reed',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 2,
  },
  {
    name: 'Grand Reed',
    desc: 'TODO',
    gameId: 'Song Reed Grand',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Choir Clapper',
    desc: 'TODO',
    gameId: 'Song Heavy Sentry',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 2,
  },
  {
    name: 'Clawmaiden',
    desc: 'TODO',
    gameId: 'Song Handmaiden',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Memoria',
    desc: 'TODO',
    gameId: 'Arborium Keeper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 2,
  },
  {
    name: 'Minister',
    desc: 'TODO',
    gameId: 'Song Administrator',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Maestro',
    desc: 'TODO',
    gameId: 'Song Pilgrim Maestro',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 2,
  },
  {
    name: 'Second Sentinel',
    desc: 'TODO',
    gameId: 'Song Knight',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Dreg Husk',
    desc: 'TODO',
    gameId: 'Song Threaded Husk',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Dregwheel',
    desc: 'TODO',
    gameId: 'Song Threaded Husk Spin',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Surgeon',
    desc: 'TODO',
    gameId: 'Song Pilgrim 02',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 2,
  },
  {
    name: 'Mortician',
    desc: 'TODO',
    gameId: 'Song Creeper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'The Unravelled',
    desc: 'TODO',
    gameId: 'Conductor Boss',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Cogwork Underfly',
    desc: 'TODO',
    gameId: 'Understore Automaton',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 25,
    act: 2,
  },
  {
    name: 'Cogwork Hauler',
    desc: 'TODO',
    gameId: 'Understore Automaton EX',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Cogwork Crawler',
    desc: 'TODO',
    gameId: 'Song Automaton Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Cogworker',
    desc: 'TODO',
    gameId: 'Song Automaton Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Cogwork Spine',
    desc: 'TODO',
    gameId: 'Song Automaton Fly Spike',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Cogwork Choirbug',
    desc: 'TODO',
    gameId: 'Song Automaton 11',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Cogwork Cleanser',
    desc: 'TODO',
    gameId: 'Song Automaton 12',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 2,
  },
  {
    name: 'Cogwork Defender',
    desc: 'TODO',
    gameId: 'Song Automaton Shield',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 2,
  },
  {
    name: 'Cogwork Clapper',
    desc: 'TODO',
    gameId: 'Song Automaton Ball',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Cogwork Dancers',
    desc: 'TODO',
    gameId: 'Clockwork Dancer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Vaultborn',
    desc: 'TODO',
    gameId: 'Song Scholar Acolyte',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Lampbearer',
    desc: 'TODO',
    gameId: 'Lightbearer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Scrollreader',
    desc: 'TODO',
    gameId: 'Scrollkeeper',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 2,
  },
  {
    name: 'Vaultkeeper',
    desc: 'TODO',
    gameId: 'Scholar',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Trobbio',
    desc: 'TODO',
    gameId: 'Trobbio',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Tormented Trobbio',
    desc: 'TODO',
    gameId: 'Tormented Trobbio',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Penitent',
    desc: 'TODO',
    gameId: 'Slab Prisoner Leaper New',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 1,
  },
  {
    name: 'Puny Penitent',
    desc: 'TODO',
    gameId: 'Slab Prisoner Fly New',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 1,
  },
  {
    name: 'Freshfly',
    desc: 'TODO',
    gameId: 'Slab Fly Small Fresh',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Scabfly',
    desc: 'TODO',
    gameId: 'Slab Fly Small',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 1,
  },
  {
    name: 'Guardfly',
    desc: 'TODO',
    gameId: 'Slab Fly Mid',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 1,
  },
  {
    name: 'Wardenfly',
    desc: 'TODO',
    gameId: 'Slab Fly Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 1,
  },
  {
    name: 'Broodmother',
    desc: 'TODO',
    gameId: 'Slab Fly Broodmother',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Driftlin',
    desc: 'TODO',
    gameId: 'Peaks Drifter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 21,
    act: 2,
  },
  {
    name: 'Mnemonid',
    desc: 'TODO',
    gameId: 'Crystal Drifter',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 2,
  },
  {
    name: 'Mnemonord',
    desc: 'TODO',
    gameId: 'Crystal Drifter Giant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 3,
    act: 3,
  },
  {
    name: 'Servitor Ignim',
    desc: 'TODO',
    gameId: 'Weaver Servitor',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 1,
  },
  {
    name: 'Servitor Boran',
    desc: 'TODO',
    gameId: 'Weaver Servitor Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 5,
    act: 2,
  },
  {
    name: 'Winged Lifeseed',
    desc: 'TODO',
    gameId: 'Lifeblood Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 1,
  },
  {
    name: 'Plasmid',
    desc: 'TODO',
    gameId: 'Bone Worm BlueBlood',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 3,
  },
  {
    name: 'Plasmidas',
    desc: 'TODO',
    gameId: 'Bone Worm BlueTurret',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Plasmified Zango',
    desc: 'TODO',
    gameId: 'Blue Assistant',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Leaf Glider',
    desc: 'TODO',
    gameId: 'Lilypad Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 12,
    act: 3,
  },
  {
    name: 'Leaf Roller',
    desc: 'TODO',
    gameId: 'Grass Goomba',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Pendra',
    desc: 'TODO',
    gameId: 'Hornet Dragonfly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Pendragor',
    desc: 'TODO',
    gameId: 'Dragonfly Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Nuphar',
    desc: 'TODO',
    gameId: 'Lilypad Trap',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Cloverstag',
    desc: 'TODO',
    gameId: 'Cloverstag',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Palestag',
    desc: 'TODO',
    gameId: 'Cloverstag White',
    img: () => <>TODO</>,
    markers: [],
    isCounted: false,
    missable: () => true,
    required: 1,
    act: 3,
  },
  {
    name: 'Kindanir',
    desc: 'TODO',
    gameId: 'Grasshopper Child',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Verdanir',
    desc: 'TODO',
    gameId: 'Grasshopper Slasher',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Escalion',
    desc: 'TODO',
    gameId: 'Grasshopper Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Clover Dancers',
    desc: 'TODO',
    gameId: 'Clover Dancer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Shadow Creeper',
    desc: 'TODO',
    gameId: 'Abyss Crawler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 16,
    act: 3,
  },
  {
    name: 'Shadow Charger',
    desc: 'TODO',
    gameId: 'Abyss Crawler Large',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 6,
    act: 3,
  },
  {
    name: 'Gloomsac',
    desc: 'TODO',
    gameId: 'Gloomfly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 15,
    act: 3,
  },
  {
    name: 'Gargant Gloom',
    desc: 'TODO',
    gameId: 'Gloom Beast',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 3,
  },
  {
    name: 'Void Tendrils',
    desc: 'TODO',
    gameId: 'Void Tendrils',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Void Mass',
    desc: 'TODO',
    gameId: 'Black Thread Core',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 8,
    act: 3,
  },
  {
    name: 'Summoned Saviour',
    desc: 'TODO',
    gameId: 'Abyss Mass',
    img: () => <>TODO</>,
    markers: [],
    isCounted: 'steel',
    required: 1,
    act: 3,
  },
  {
    name: 'Wingmould',
    desc: 'TODO',
    gameId: 'White Palace Fly',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Garpid',
    desc: 'TODO',
    gameId: 'Centipede Trap',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 31,
    act: 3,
  },
  {
    name: 'Imoba',
    desc: 'TODO',
    gameId: 'Spike Lazy Flyer',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 4,
    act: 3,
  },
  {
    name: 'Skrill',
    desc: 'TODO',
    gameId: 'Surface Scuttler',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 11,
    act: 3,
  },
  {
    name: 'Bell Eater',
    desc: 'TODO',
    gameId: 'Giant Centipede',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Huge Flea',
    desc: 'TODO',
    gameId: 'Giant Flea',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Shakra',
    desc: 'TODO',
    gameId: 'Shakra',
    img: () => <>TODO</>,
    markers: [],
    isCounted: false,
    missable: () => true,
    required: 1,
    act: 2,
  },
  {
    name: 'Garmond & Zaza',
    desc: 'TODO',
    gameId: 'Garmond_Zaza',
    img: () => <>TODO</>,
    markers: [],
    isCounted: false,
    missable: () => true,
    required: 1,
    act: 2,
  },
  {
    name: 'Lost Garmond',
    desc: 'TODO',
    gameId: 'Garmond',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Pinstress',
    desc: 'TODO',
    gameId: 'Pinstress Boss',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 3,
  },
  {
    name: 'Widow',
    desc: 'TODO',
    gameId: 'Spinner Boss',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'First Sinner',
    desc: 'TODO',
    gameId: 'First Weaver',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Phantom',
    desc: 'TODO',
    gameId: 'Phantom',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 1,
  },
  {
    name: 'Lace',
    desc: 'TODO',
    gameId: 'Lace',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 2,
    act: 2,
  },
  {
    name: 'Grand Mother Silk',
    desc: 'TODO',
    gameId: 'Silk Boss',
    img: () => <>TODO</>,
    markers: [],
    isCounted: true,
    required: 1,
    act: 2,
  },
  {
    name: 'Lost Lace',
    desc: 'TODO',
    gameId: 'Lost Lace',
    img: () => <>TODO</>,
    markers: [],
    isCounted: false,
    required: 1,
    act: 3,
  },
];
