export enum ToolType {
  Red = 0,
  Blue = 1,
  Yellow = 2,
  SilkSkill = 3,
}

export const Tools: Record<
  string,
  { id: string; displayName: string; isCounted: boolean; type: ToolType }
> = {
  'Barbed Wire': {
    id: 'Barbed Wire',
    displayName: 'Barbed Bracelet',
    isCounted: true,
    type: 2,
  },
  'Bell Bind': {
    id: 'Bell Bind',
    displayName: 'Warding Bell',
    isCounted: true,
    type: 1,
  },
  'Bone Necklace': {
    id: 'Bone Necklace',
    displayName: 'Shard Pendant',
    isCounted: true,
    type: 2,
  },
  'Brolly Spike': {
    id: 'Brolly Spike',
    displayName: 'Sawtooth Circlet',
    isCounted: true,
    type: 1,
  },
  'Cogwork Flier': {
    id: 'Cogwork Flier',
    displayName: 'Cogfly',
    isCounted: true,
    type: 0,
  },
  'Cogwork Saw': {
    id: 'Cogwork Saw',
    displayName: 'Cogwork Wheel',
    isCounted: true,
    type: 0,
  },
  Compass: {
    id: 'Compass',
    displayName: 'Compass',
    isCounted: true,
    type: 2,
  },
  'Conch Drill': {
    id: 'Conch Drill',
    displayName: 'Conchcutter',
    isCounted: true,
    type: 0,
  },
  'Curve Claws Upgraded': {
    id: 'Curve Claws Upgraded',
    displayName: 'Curvesickle',
    isCounted: true,
    type: 0,
  },
  'Curve Claws': {
    id: 'Curve Claws',
    displayName: 'Curveclaw',
    isCounted: true,
    type: 0,
  },
  'Dazzle Bind Upgraded': {
    id: 'Dazzle Bind Upgraded',
    displayName: 'Claw Mirrors',
    isCounted: true,
    type: 1,
  },
  'Dazzle Bind': {
    id: 'Dazzle Bind',
    displayName: 'Claw Mirror',
    isCounted: true,
    type: 1,
  },
  'Dead Mans Purse': {
    id: 'Dead Mans Purse',
    displayName: "Dead Bug's Purse",
    isCounted: true,
    type: 2,
  },
  Extractor: {
    id: 'Extractor',
    displayName: 'Extractor',
    isCounted: false,
    type: 0,
  },
  'Flea Brew': {
    id: 'Flea Brew',
    displayName: 'Flea Brew',
    isCounted: true,
    type: 0,
  },
  'Flea Charm': {
    id: 'Flea Charm',
    displayName: 'Egg of Flealia',
    isCounted: true,
    type: 1,
  },
  Flintstone: {
    id: 'Flintstone',
    displayName: 'Flintslate',
    isCounted: true,
    type: 0,
  },
  'Fractured Mask': {
    id: 'Fractured Mask',
    displayName: 'Fractured Mask',
    isCounted: true,
    type: 1,
  },
  Harpoon: {
    id: 'Harpoon',
    displayName: 'Longpin',
    isCounted: true,
    type: 0,
  },
  'Lava Charm': {
    id: 'Lava Charm',
    displayName: 'Magma Bell',
    isCounted: true,
    type: 1,
  },
  'Lifeblood Syringe': {
    id: 'Lifeblood Syringe',
    displayName: 'Plasmium Phial',
    isCounted: true,
    type: 0,
  },
  'Lightning Rod': {
    id: 'Lightning Rod',
    displayName: 'Voltvessels',
    isCounted: true,
    type: 0,
  },
  Longneedle: {
    id: 'Longneedle',
    displayName: 'Longclaw',
    isCounted: true,
    type: 1,
  },
  'Maggot Charm': {
    id: 'Maggot Charm',
    displayName: 'Wreath of Purity',
    isCounted: true,
    type: 1,
  },
  'Magnetite Dice': {
    id: 'Magnetite Dice',
    displayName: 'Magnetite Dice',
    isCounted: true,
    type: 2,
  },
  'Mosscreep Tool 1': {
    id: 'Mosscreep Tool 1',
    displayName: "Druid's Eye",
    isCounted: true,
    type: 1,
  },
  'Mosscreep Tool 2': {
    id: 'Mosscreep Tool 2',
    displayName: "Druid's Eyes",
    isCounted: true,
    type: 1,
  },
  Multibind: {
    id: 'Multibind',
    displayName: 'Multibinder',
    isCounted: true,
    type: 1,
  },
  'Musician Charm': {
    id: 'Musician Charm',
    displayName: 'Spider Strings',
    isCounted: true,
    type: 2,
  },
  Parry: {
    id: 'Parry',
    displayName: 'Cross Stitch',
    isCounted: true,
    type: 3,
  },
  Pimpilo: {
    id: 'Pimpilo',
    displayName: 'Pimpillo',
    isCounted: true,
    type: 0,
  },
  'Pinstress Tool': {
    id: 'Pinstress Tool',
    displayName: 'Pin Badge',
    isCounted: true,
    type: 1,
  },
  'Poison Pouch': {
    id: 'Poison Pouch',
    displayName: 'Pollip Pouch',
    isCounted: true,
    type: 1,
  },
  'Quick Sling': {
    id: 'Quick Sling',
    displayName: 'Quick Sling',
    isCounted: true,
    type: 1,
  },
  Quickbind: {
    id: 'Quickbind',
    displayName: 'Injector Band',
    isCounted: true,
    type: 1,
  },
  'Reserve Bind': {
    id: 'Reserve Bind',
    displayName: 'Reserve Bind',
    isCounted: true,
    type: 1,
  },
  'Revenge Crystal': {
    id: 'Revenge Crystal',
    displayName: 'Memory Crystal',
    isCounted: true,
    type: 1,
  },
  'Rosary Cannon': {
    id: 'Rosary Cannon',
    displayName: 'Rosary Cannon',
    isCounted: true,
    type: 0,
  },
  'Rosary Magnet': {
    id: 'Rosary Magnet',
    displayName: 'Magnetite Brooch',
    isCounted: true,
    type: 2,
  },
  'Screw Attack': {
    id: 'Screw Attack',
    displayName: "Delver's Drill",
    isCounted: true,
    type: 0,
  },
  Scuttlebrace: {
    id: 'Scuttlebrace',
    displayName: 'Scuttlebrace',
    isCounted: true,
    type: 2,
  },
  'Shakra Ring': {
    id: 'Shakra Ring',
    displayName: 'Throwing Ring',
    isCounted: true,
    type: 0,
  },
  'Shell Satchel': {
    id: 'Shell Satchel',
    displayName: 'Shell Satchel',
    isCounted: true,
    type: 2,
  },
  'Silk Bomb': {
    id: 'Silk Bomb',
    displayName: 'Rune Rage',
    isCounted: true,
    type: 3,
  },
  'Silk Boss Needle': {
    id: 'Silk Boss Needle',
    displayName: 'Pale Nails',
    isCounted: true,
    type: 3,
  },
  'Silk Charge': {
    id: 'Silk Charge',
    displayName: 'Sharpdart',
    isCounted: true,
    type: 3,
  },
  'Silk Snare': {
    id: 'Silk Snare',
    displayName: 'Silk Snare',
    isCounted: false,
    type: 0,
  },
  'Silk Spear': {
    id: 'Silk Spear',
    displayName: 'Silk Spear',
    isCounted: true,
    type: 3,
  },
  'Spool Extender': {
    id: 'Spool Extender',
    displayName: 'Spool Extender',
    isCounted: true,
    type: 1,
  },
  Sprintmaster: {
    id: 'Sprintmaster',
    displayName: 'Silkspeed Anklets',
    isCounted: true,
    type: 2,
  },
  'Sting Shard': {
    id: 'Sting Shard',
    displayName: 'Sting Shard',
    isCounted: true,
    type: 0,
  },
  'Straight Pin': {
    id: 'Straight Pin',
    displayName: 'Straight Pin',
    isCounted: true,
    type: 0,
  },
  Tack: {
    id: 'Tack',
    displayName: 'Tacks',
    isCounted: true,
    type: 0,
  },
  'Thief Charm': {
    id: 'Thief Charm',
    displayName: "Thief's Mark",
    isCounted: true,
    type: 2,
  },
  'Thief Claw': {
    id: 'Thief Claw',
    displayName: 'Snitch Pick',
    isCounted: true,
    type: 1,
  },
  'Thread Sphere': {
    id: 'Thread Sphere',
    displayName: 'Thread Storm',
    isCounted: true,
    type: 3,
  },
  'Tri Pin': {
    id: 'Tri Pin',
    displayName: 'Threefold Pin',
    isCounted: true,
    type: 0,
  },
  Wallcling: {
    id: 'Wallcling',
    displayName: "Ascendant's Grip",
    isCounted: true,
    type: 2,
  },
  'WebShot Architect': {
    id: 'WebShot Architect',
    displayName: 'Silkshot',
    isCounted: true,
    type: 0,
  },
  'WebShot Forge': {
    id: 'WebShot Forge',
    displayName: 'Silkshot',
    isCounted: true,
    type: 0,
  },
  'WebShot Weaver': {
    id: 'WebShot Weaver',
    displayName: 'Silkshot',
    isCounted: true,
    type: 0,
  },
  'Weighted Anklet': {
    id: 'Weighted Anklet',
    displayName: 'Weighted Belt',
    isCounted: true,
    type: 2,
  },
  'White Ring': {
    id: 'White Ring',
    displayName: 'Weavelight',
    isCounted: true,
    type: 1,
  },
  'Wisp Lantern': {
    id: 'Wisp Lantern',
    displayName: 'Wispfire Lantern',
    isCounted: true,
    type: 1,
  },
  'Zap Imbuement': {
    id: 'Zap Imbuement',
    displayName: 'Volt Filament',
    isCounted: true,
    type: 1,
  },
};
